### ISSUE TITLE
UI does not appear

### ISSUE THREAD

**Issue by bezsahara** [WarningImHack3r/intellij-shadcn-plugin#62]
### Issue type

Problem

### Description

I have components.json but UI does not appear on the plugin. I use RustRover 2024.2 EAP (#RR-242.21829.114). 
![image](https://github.com/user-attachments/assets/020d3084-8e78-4857-a1b5-c54fcb18b574)
![image](https://github.com/user-attachments/assets/1e1f0dc1-02e0-4437-b195-6b41c6c2b59a)

### Special case

- [X] This is not a bug nor a feature request, I can't use other templates

**Comment by WarningImHack3r** [comment]
Hi there, thanks for reporting! My first guess is that the Windows path you have for the CSS file breaks the thing, I’ll try to reproduce it myself with this exact file.

I’ll keep you updated if I do, otherwise I’ll need your logs!

**Comment by WarningImHack3r** [comment]
Sorry for the delay! The problem was not from the CSS path (I never actually use it in my code), but rather from the `typescript` option.
I was looking for the `.svelte-kit/jsconfig.json` as `typescript` is `false` in your `components.json`; in a similar fashion to what `shadcn-svelte`does.

However, `.svelte-kit` **always** [uses tsconfig.json](https://github.com/sveltejs/kit/blob/main/packages/kit/src/core/sync/write_tsconfig.js#L41), so I simply needed to change that path to make it work properly.
